services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - all
    restart: on-failure
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - all
    restart: on-failure
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - mariadb
    
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress:/var/www/html
    ports:
      - "443:443"
    networks:
      - all
    restart: on-failure
    depends_on:
      - wordpress

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ${DB_PATH}
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ${WP_PATH}
      o: bind

networks:
  all:
    driver: bridge
